version: '3'
services:
  nginx:
   build: ./NGINX
    #volumes:
    #  - /var/lib/postgresql/data
   ports:
     - "80:80"

  db:
    build: ./POSTGRES
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  appx:
    build: ./APPX
    #command: bash  -c "dotnet run --urls https://0.0.0.0:5000"
    command: bash  -c "dotnet ef database update"
    #volumes:
    #   - .:/myapp
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
