version: '3'
services:
  nginx:
   build: ./NGINX
    #volumes:
    #  - /var/lib/postgresql/data
   ports:
     - "80:80"
  appx:
    build: ./APPX
    #command: bash  -c "dotnet run --urls https://0.0.0.0:5000"
    #volumes:
    #   - .:/myapp
    ports:
      - "5000:5000"
      - "5001:5001"
   # depends_on:
   #   - nginx

      